### ISSUE TITLE
[bug][minor] Improper markdown highlighting in nested nodes

### ISSUE THREAD

**Issue by Varun0157** [harrydowning/yaml-embedded-languages#13]
I am developing an extension that allows users to create and document API requests. 

I noticed that on attempting to syntactically highlight markdown in nested nodes, a lot of the text (beyond the first line is what I've noticed) gets treated as regular text, regardless of whether it is a header, bullet point etc. The example will make it easier to understand.  

Minimum reproducible example:
```
key:
  doc: | # markdown
    # header // highlighted
    content
    # header // not highlighted
    content
```
![image](https://github.com/harrydowning/yaml-embedded-languages/assets/125901917/f5293fe1-3e39-4145-9a94-d0fe7b1f5488)

Another example:
![image](https://github.com/harrydowning/yaml-embedded-languages/assets/125901917/5579095b-be56-4a35-8803-6303166818b4)

- The extension works correctly if the `doc` node is not nested. 
- In general, the issue seems to occur if the text block starts with any kind of header.
- I have the [RedHat YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) extension installed, but I doubt it is interfering because this does not work without it either.
- The textmate scope of the second header in the minimum reproducible example does *not* denote it as a header. 

For a larger example, you may try out your extension on [this file](https://github.com/agrostar/zzapi/blob/f6d37ee225e228d380035786be919be94c328066/examples/docs-bundle.zzb).

VSCode version: 1.85.1

**Comment by RedCMD** [comment]
you would need to capture the prefixing whitespace (indentation) to fix it fully.
change `begin`/`end` to [while](https://github.com/RedCMD/TmLanguage-Syntax-Highlighter/blob/main/documentation/rules.md#while)
`"while": "(^|\\G)( +|$)` or something
https://github.com/RedCMD/YAML-Syntax-Highlighter/blob/823ec390bcb97538088f84285484ee9f37c40def/syntaxes/yaml-1.2.tmLanguage.json#L393-L498
